name: talk_stream_backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  broadcast_bloc: ^0.1.0-dev.2
  dart_frog: ^0.3.0
  dart_frog_web_socket: ^0.1.0-dev.3
  auth_data_source:
    path: packages/auth_data_source
  chat_data_source:
    path: packages/chat_data_source

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
