name: auth_data_source
description: My new Dart package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.3.3
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
dependencies:
  collection: ^1.17.1
  equatable: ^2.0.5
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  meta: ^1.9.0
  uuid: ^3.0.7
